### ISSUE TITLE
Uninitialized pointers used in code overwrite memory at 0x00000000 in memory

### ISSUE THREAD

**Issue by mpetch** [sasdallas/reduceOS#8]
I had created code that remaps the PICs so code in BIOS32 could run (and restore them after) with interrupts on while in real mode when I discovered some serious issues with memory at 0x00000000 being overwritten with garbage. I discovered that in a number of places in the code you don't assign an address to a pointer and most often that results in memory at 0x00000000 being written to. In other places you assign a pointer not with allocated memory but with NULL values. All these possible bugs can add up to unusual behaviour potentially occurring.

The most prevalent place to observe this is in is terminal.c. Find the occurrences of `char *s = {0};` and `char *str = {0};` . This set s to NULL(0) and then you use that memory (with a strcpy). You'd normally have to allocate memory but in the 2 cases in terminal.c the code can be simplified.

This existing code in terminal.c:
```
// %s is for strings (or address of).
case 's': {
    const char *c = va_arg(args, const char *); // Char promotes to integer, and we're trying to get the address of the string.
    char *str = {0}; // The array where the character will go.

    strcpy(str, (const char *)c); // Copy c to str (dest is the first parameter)
    
    if (!print(str, strlen(str))) return -1; // Print error!

    charsWritten++; // Increment charsWritten
    i++; // Increment i.
    break;
}
```
Can be replaced with:
```
// %s is for strings (or address of).
case 's': {
    const char *c = va_arg(args, const char *); // Char promotes to integer, and we're trying to get>
    if (!print(c, strlen(c))) return -1; // Print error!

    charsWritten += strlen(c); // Increment charsWritten
    i++; // Increment i.
    break;
}
```
and:

```
// %s is for strings (or address of).
case 's': {
    const char *c = va_arg(args, const char *); // Char promotes to integer, and we're trying to get the address of the string.
    char *s = {0}; // The array where the character will go.

    strcpy(s, (const char *)c); // Copy c to str (dest is the first parameter)
    
    for (int i = 0; i < strlen(s); i++) {
        put_method(s[i]);
    }
    charsWritten++; // Increment charsWritten
    i++; // Increment i.
    break;
}
```
Can be replaced with:
```
// %s is for strings (or address of).
case 's': {
    const char *c = va_arg(args, const char *); // Char promotes to integer, and we're trying to get>
    for (int i = 0; i < strlen(c); i++) {
        put_method(c[i]);
    }
    charsWritten += strlen(c); // Increment charsWritten
    i++; // Increment i.
    break;
}
```
In this case I removed `strcpy` altogether and just use the const *c directly. As well you will notice I properly update `charsWritten` with the actual number of characters printed (as you just added 1).  You may wish to look at all the places where you output more than one character and add the appropriate number of characters written. I noticed this in cases where `itoa` is called and `charsWritten` is not updated correctly with the actual number of characters written.

Two other places where a pointer isn't initialized and writes are made to 0x00000000 occur. In processor.c you have `static cpuInfo_t *processor_data;` . This pointer is never initialized anywhere with `kmalloc` for example or your code could use `static cpuInfo_t processor_data;` to allocate the memory in global memory. Then all places you use `processor_data->` would become `processor_data.` . You have a similar problem with `sse5_Data` in the `processor_data` structure.. `sse5_data` is defined as a pointer but it is never initialized to allocated memory. In ide_ata.c a similar issue with `ataRoot`. You do `fsNode_t *ataRoot;` but this pointer is never set to initialized memory before being used.

There is a potential use of `framebuffer` before it is initialized in pit.c . This code:
```
// PIT timer interrupt handler
void pitIRQ() { 
    pitTicks++; // Increment tick count
    updateTextCursor_vesa(); // To be replaced with some sort of handler/caller list
}
```
Should be:
```
// PIT timer interrupt handler
void pitIRQ() {
    pitTicks++; // Increment tick count
    if (terminalMode == 1)
        updateTextCursor_vesa(); // To be replaced with some sort of handler/caller list
}
```
If you use `updateTextCursor_vesa()` before the framebuffer pointer is set then you will be accessing memory through an uninitialized pointer.

**Comment by sasdallas** [comment]
@mpetch Thank you for pointing this out! This information will prove very useful - `kmalloc()` was giving a lot of trouble, and due to issues with liballoc, the new memory allocator and BIOS32 (as always haha), I was more focused on that. While I will throw on a temporary fix, do you have an idea on a way to implement memory allocation without actually having it initialized yet (since it is initialized later)? My current approach is very naive, and is likely overwriting pages and not telling the actual handler, and that's not good, but liballoc faults BIOS32.

**Comment by sasdallas** [comment]
Right now, the repo can be built and tests do (for the most part) pass, but the underlying base is bad, and from experience (cough stackoverflow issue cough), a bad underlying base is just a catastrophe waiting to happen. These problems are very helpful and these parts of the code were always ones that caused issues! Thank you so much!

**Comment by sasdallas** [comment]
Temporary patch applied.

**Comment by sasdallas** [comment]
During further investigation, I have discovered that BIOS32 may not be the culprit. I implemented a small function to service interrupt 0x15 (AX = 0xE801, should return memory info) and it serviced fine and even returned correct values.

**Comment by mpetch** [comment]
> During further investigation, I have discovered that BIOS32 may not be the culprit. I implemented a small function to service interrupt 0x15 (AX = 0xE801, should return memory info) and it serviced fine and even returned correct values.

If you call functions that were overwriting memory at 0x00000000 before calling BIOS32, the interrupt Vector table could be clobbered and real mode BIOS and external interrupts may not work properly because the vectors have potentially been overwritten with garbage. I discovered this very issue because I tried to write code to properly enable interrupts when back in real mode and it crashed. Depending on what interrupts get clobbered some may appear to work and others may not.

**Comment by sasdallas** [comment]
@mpetch Yes, you are correct. I'm working on that non-present code now. Another problem though is that things like ACPI do not properly map their pages so doing anything with ACPI after paging is enabled page faults. I tried to move memory management as far back in the init process as I could but then `initrd` freaks out. I'm trying to solve this issue too.

**Comment by sasdallas** [comment]
ACPI can easily be fixed with a few `vmm_allocateRegion` calls, but those can only be done after VMM is initialized. initrd can be patched with another `vmm_allocateRegion` call, but then the system freaks out or just stops.

**Comment by sasdallas** [comment]
Bug in initrd revolves around file amounts. Disabling for now reveals more bugs in FAT driver, but otherwise system CAN start up.

**Comment by sasdallas** [comment]
The bug in initrd is not within the generator, but rather apparently address calculation is not working.

**Comment by sasdallas** [comment]
It appears that, for now, the OS is stable.
I've also marked pages as non-present in the first 4kb as you suggested, and have added test modules to test specific parts of code. Thank you!
